import axios from 'axios';
import { useEffect, useState } from 'react';
export default function Home(){
  const apiBase = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4000/api';
  const [packages, setPackages] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showAd, setShowAd] = useState(null);
  const [aiQuestion, setAiQuestion] = useState('');
  const [aiAnswer, setAiAnswer] = useState('');
  useEffect(()=>{ async function load(){ try{ const res = await axios.get(apiBase + '/packages'); setPackages(res.data); }catch(e){ console.error(e);} finally{ setLoading(false);} } load(); },[apiBase]);
  async function buy(pkg){ const phone = prompt('Enter phone number (e.g. 2547...)'); if(!phone) return; try{ const res = await axios.post(apiBase + '/purchase', { package_id: pkg.id, phone }); if(res.data && res.data.ok){ setShowAd(res.data.ad); alert('Purchase success! Voucher: ' + (res.data.voucher||res.data.external_id)); } else alert('Purchase failed'); }catch(e){ alert('Error purchasing'); console.error(e); } }
  async function askAi(){ if(!aiQuestion) return; try{ const res = await axios.post(apiBase + '/ai', { question: aiQuestion }); setAiAnswer(res.data.answer); }catch(e){ setAiAnswer('AI error'); } }
  return (<div className='container'><header className='header'><div className='logo'><img src='/logo.svg' width='96' alt='EdgeFi'/></div><div><div className='h1'>EdgeFi — Connect & Earn</div><div style={{color:'#555'}}>Buy WiFi, support partners, get online fast</div></div></header><main><h2 style={{marginTop:18}}>Packages</h2>{loading ? <p>Loading packages...</p> : <div className='grid'>{packages.map(p=>(<div className='card' key={p.id}><h3>{p.name}</h3><p style={{color:'#666'}}>Duration: {p.duration_hours} hrs • Type: {p.type}</p><div style={{display:'flex',gap:8,marginTop:12}}><button className='btn-3d' onClick={()=>buy(p)}>Buy — KES {p.price}</button></div></div>))}</div>}</main><div className='help-pill'><a href='https://wa.me/254700000000?text=Hi%20EdgeFi%20Support' target='_blank' style={{color:'#fff',textDecoration:'none'}}>WhatsApp</a><a href='sms:+254700000000' style={{color:'#fff',marginLeft:10}}>SMS</a><a href='tel:+254700000000' style={{color:'#fff',marginLeft:10}}>Call</a></div><div className='ai-panel'><div style={{fontWeight:700}}>NeuroEdge AI</div><textarea rows={2} value={aiQuestion} onChange={(e)=>setAiQuestion(e.target.value)} placeholder='Ask NeuroEdge AI' style={{width:240}}></textarea><div style={{display:'flex',gap:8,marginTop:8}}><button onClick={askAi} className='btn-3d'>Ask AI</button><button onClick={()=>{setAiQuestion('');setAiAnswer('');}} className='btn-3d' style={{background:'#ccc'}}>Clear</button></div>{aiAnswer && <div style={{marginTop:8,padding:8,background:'#f8f8f8',borderRadius:8}}>{aiAnswer}</div>}</div>{showAd && <div className='ad-overlay' onClick={()=>setShowAd(null)}><div className='ad-card'><img src={showAd.image} width='300' alt='ad'/><h3>{showAd.title}</h3><a href={showAd.url} target='_blank'>Learn more</a></div></div>}</div>); }
